apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-app-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-app-k8s
  template:
    metadata:
      labels:
        app: ecom-app-k8s
    spec:
      containers:
        - name: ecom-app-k8s
          image: basu122/e-commerce-docker
          ports:
            - containerPort: 8084


---

apiVersion: v1
kind: Service
metadata:
  name: ecom-app-k8s-service
spec:
  type: NodePort
  selector:
    app: ecom-app-k8s
  ports:
    - port: 80
      targetPort: 8084
      nodePort: 30007
